import os

# PRIMARY AZURE OPENAI CONNECTION DETAILS
AZURE_OPENAI_KEY=os.environ.get('AZURE_OPENAI_KEY')
AZURE_OPENAI_ENDPOINT=os.environ.get('AZURE_OPENAI_ENDPOINT')

# BACKUP AZURE OPENAI CONNECTION DETAILS
AZURE_OPENAI_BACKUP_KEY=os.environ.get('AZURE_OPENAI_BACKUP_KEY')
AZURE_OPENAI_BACKUP_ENDPOINT=os.environ.get('AZURE_OPENAI_BACKUP_ENDPOINT')

# SQL SERVER CONNECTIONS
SQL_SERVER = os.environ.get('SQL_SERVER')
SQL_DATABASE = os.environ.get('SQL_DATABASE')
SQL_USERNAME = os.environ.get('SQL_USERNAME')
SQL_PASSWORD = os.environ.get('SQL_PASSWORD')

#MICROSOFT GRAPH API CONFIGS
CLIENT_ID = os.environ.get('CLIENT_ID')
TENANT_ID = os.environ.get('TENANT_ID')
CLIENT_SECRET = os.environ.get('CLIENT_SECRET')
AUTHORITY = f'https://login.microsoftonline.com/{TENANT_ID}'
SCOPE = ['https://graph.microsoft.com/.default']

# EMAIL CONFIGURATIONS
EMAIL_ACCOUNTS = [os.environ.get('EMAIL_ACCOUNT')]
DEFAULT_EMAIL_ACCOUNT = 'tevinri@tihsa.co.za'

# INTERVAL IN SECONDS(30) 
EMAIL_FETCH_INTERVAL = 30

# AZURE BLOB STORAGE SETTINGS
AZURE_STORAGE_CONNECTION_STRING = os.environ.get('AZURE_STORAGE_CONNECTION_STRING')
BLOB_CONTAINER_NAME = os.environ.get('BLOB_CONTAINER_NAME')
AZURE_STORAGE_PUBLIC_URL = os.environ.get('AZURE_STORAGE_PUBLIC_URL')  # Public URL for blob storage account

# Import the routing configurations
POLICY_SERVICES=os.environ.get('POLICY_SERVICES')
TRACKING_MAILS=os.environ.get('TRACKING_MAILS')
CLAIMS_MAILS=os.environ.get('CLAIMS_MAILS')
ONLINESUPPORT_MAILS=os.environ.get('ONLINESUPPORT_MAILS')
INSURANCEADMIN_MAILS=os.environ.get('INSURANCEADMIN_MAILS')
DIGITALCOMMS_MAILS=os.environ.get('DIGITALCOMMS_MAILS')
CONNEX_TEST=os.environ.get('CONNEX_TEST')

# Configure the mail-template mappings for autoresponse mails
EMAIL_TO_FOLDER_MAPPING = {
    ONLINESUPPORT_MAILS: "onlinesupport",
    POLICY_SERVICES: "policyservice",
    TRACKING_MAILS: "tracking",
    DIGITALCOMMS_MAILS: "digitalcomms",
    CLAIMS_MAILS: "claims",

}
